### ISSUE TITLE
"Temporarily sizing and moving the dialog..." alert should be a console.log instead

### ISSUE THREAD

**Issue by HigherFive** [jonnyrobbie/Reddit-Comment-Faces-Helper#1]
The specific call is on [line 1758 in comment_faces_helper.user.js](https://github.com/jonnyrobbie/Reddit-Comment-Faces-Helper/blob/2bc2cd37b972703a27cd798afb82a89abc7d247f/comment_faces_helper.user.js#L1758).

The alert box obstructs regular usage and it conveys no critical information, so it should probably be replaced with a console message or removed entirely.

**Comment by jonnyrobbie** [comment]
Yeah, the idea was that when you resize browser window so that the faces dialog no longer fits, I thought it might be nice to let user know that I'll temporarily override his position settings.

I rarely resize browser window, so it didn't really occur to me it might be annoying.

**Comment by HigherFive** [comment]
Ah, I see. I didn't realize the values displayed in the settings table
changed as well. Maybe the message should appear as a note in there?

**Comment by jonnyrobbie** [comment]
I may just changed it to a simpe `console.log` like you originally suggested.

**Comment by HigherFive** [comment]
That's good enough for me
