### ISSUE TITLE
Lots of faces missing from /r/anime, could be more in others

### ISSUE THREAD

**Issue by Atario** [jonnyrobbie/Reddit-Comment-Faces-Helper#3]
There are a lot of /r/anime faces not listed in the Helper, almost all of them being the ones with hyphens in them:

> ```
> araragi-1
> araragi-2
> asuka-shouting
> blank-stare
> bot-chan
> chaika-smile
> chiho-wut
> chitoge-pissed
> chiyo-uhh
> dead-eyed-stare
> deko-cry
> exuberant-shu
> gamagori-hnng
> gendo-pls
> glasses-push
> haruhi-annoyed
> head-tilt
> heart-thumbs-up
> im-listening
> k-on-hug
> kanie-disgust
> kyon-facepalm
> manly-tears
> mugi-fish
> nanami-hug
> nico-heart
> not-raining
> om-nom
> pika-dead
> she-ded
> sonico-wink
> sparkle-ika
> super-blush
> super-happy
> surprised-blush
> thumbs-up
> u-dont-say
> u-wat-m8
> ugh-peasants
> wide-face
> wow-really
> you-bore-me
> yui-crying
> ```

In addition, this one is missing:

> ```
> notalolicon
> ```

**Comment by jonnyrobbie** [comment]
I'll look into that. The sheer amount of them makes it difficult to manage.

---------- Původní zpráva ----------

Od: Atario notifications@github.com

Komu: jonnyrobbie/Reddit-Comment-Faces-Helper <Reddit-Comment-Faces-Helper@
noreply.github.com>

Datum: 15. 9. 2015 22:33:05

Předmět: [Reddit-Comment-Faces-Helper] Lots of faces missing from /r/anime, 
could be more in others (#3)

"

There are a lot of /r/anime faces not listed in the Helper, almost all of 
them being the ones with hyphens in them:
" 
 araragi-1
araragi-2
asuka-shouting
blank-stare
bot-chan
chaika-smile
chiho-wut
chitoge-pissed
chiyo-uhh
dead-eyed-stare
deko-cry
exuberant-shu
gamagori-hnng
gendo-pls
glasses-push
haruhi-annoyed
head-tilt
heart-thumbs-up
im-listening
k-on-hug
kanie-disgust
kyon-facepalm
manly-tears
mugi-fish
nanami-hug
nico-heart
not-raining
om-nom
pika-dead
she-ded
sonico-wink
sparkle-ika
super-blush
super-happy
surprised-blush
thumbs-up
u-dont-say
u-wat-m8
ugh-peasants
wide-face
wow-really
you-bore-me
yui-crying

" 
In addition, this one is missing:
" 
 notalolicon

" 
—

Reply to this email directly or view it on GitHub
(https://github.com/jonnyrobbie/Reddit-Comment-Faces-Helper/issues/3). 

"=

**Comment by jonnyrobbie** [comment]
Should be done. If you see any more missing, don't hesitate to let me know.
