### ISSUE TITLE
The "Add a comment face" link stopped working

### ISSUE THREAD

**Issue by Atario** [jonnyrobbie/Reddit-Comment-Faces-Helper#6]
At least in /r/anime.  I didn't try the others yet

>     20:19:52.747 TypeError: thisLink.parentNode is undefined 1 comment_faces_helper.user.js:2527:1
>    	showSelect comment_faces_helper.user.js:2527:1
>    	showSelectFunction comment_faces_helper.user.js:2567:37
>    	u https://www.redditstatic.com/webcomponents.xriNycXog0M.js:1:12165

**Comment by jonnyrobbie** [comment]
Thanks. should be fixed now...I hope
