### ISSUE TITLE
Firefox 57 broke it

### ISSUE THREAD

**Issue by Atario** [jonnyrobbie/Reddit-Comment-Faces-Helper#9]
Pressing "Add face" does nothing now.  (N.B.:  with 56 I was using Greasemonkey but with 57 I'm using Tampermonkey.  Dunno if that makes a difference.)

**Comment by jonnyrobbie** [comment]
On Nightly, which is 59+, and it works fine for me :/ using Violentmonkey. Tampermonkey is non-free and shouldn't be used anyway. I believe even Greasemonkey should be ported too now.

**Comment by HigherFive** [comment]
I can confirm that it works fine in FF 57 with the updated Greasemonkey 4.

**Comment by Atario** [comment]
Sorry, it has started working on its own now.  No clue what happened.  Disregard, I guess!
